# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: khj0704@gmail.com
brand: HyunJun Kim
headline: Android Developer
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://blog.daum.net/creazier" # the base hostname & protocol for your site
#copyright: 2016 Whatever Company, Inc. All Rights Reserved.
copyright: 2017 khj0704(Freelancer). All Rights Reserved.

# Build settings
markdown: kramdown

# character set
encoding: UTF-8

# Account ids
snapwidget: 247552

# Contacts 
email: khj0704@gmail.com
# phone: +82-010-9327-7794
phone: 

# Tracking
# googleAnalitycsID: UA-83933844-1
googleAnalitycsID: 